name: Test SSH Command execution
run-name: Config update for "${{ inputs.environment }}" environment by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to update config'
        type: environment
        required: true

jobs:
  Run-file-creation-on-SSH-host:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ vars.SSH_USER }}
      REPO_DIR: ${{ github.action_path }}
    steps:
#      - name: Configure SSH
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$SSH_KEY" > ~/.ssh/staging.key
#          chmod 600 ~/.ssh/staging.key
#          cat >> ~/.ssh/config <<END
#          Host staging
#            HostName $SSH_HOST
#            User $SSH_USER
#            IdentityFile ~/.ssh/staging.key
#            StrictHostKeyChecking no
#          END
#      - name: Print SSH KEY
#        run: echo "$SSH_KEY"
#      - name: Print SSH HOST
#        run: echo "$SSH_HOST"
#      - name: Print SSH USER
#        run: echo "$SSH_USER"
      - name: Print workflow dir
        run: echo "$REPO_DIR"
      - name: Check workflow directory
        run: ls -la $REPO_DIR
#      - name: Run test command
#        run: ssh staging 'echo "hello there" >> github-runner-was-here.txt'